version: "3.3"

services:
  db:
    container_name: dbPostgresTodoList
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234cinco
      - POSTGRES_DB=tolistdb
    networks:
      - todolist
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: todolist
    container_name: todolist-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todolist
    depends_on:
      - "db"
  nginx:
    image: nginx:alpine
    container_name: todolist-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./application:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - todolist
    
networks:
  todolist:
    driver: bridge