version: "3.8"
services:
  db:
    container_name: dbPostgresTodoList
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234cinco
      - POSTGRES_DB=tolistdb
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: todolist
    container_name: todolist-app
    restart: always
    working_dir: /var/www/application/
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: todolist-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./application:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/